### ISSUE TITLE
can i weite an issue on the save features?

### ISSUE THREAD

**Issue by seanathen** [keyraven/clangen_catmaker#5]
im new to this site, and dont really know how to navigate it, so i dont know if you've addressed this before or not.
so ive been playing the catmaker with save features and have had a few issues,
1, there are a few screens ive been unable to leave like the ''export to clangen'' when ive accidently clicked it, and the ''export image'' screen. i have to close the game and reopen it to create a new cat.
2. when your on the tortie options and you click ''done'' the options are stuck on screen even when you go back from the initial ''done'' screen
that is all, hope this isnt bothersome.

**Comment by keyraven** [comment]
The save features is a WIP branch, and it not in a playable form.  I do not suggest running it.
